### ISSUE TITLE
Cover image properties got moved to figure container (incorrect)

### ISSUE THREAD

**Issue by aormsby** [panr/hugo-theme-hello-friend#186]
Previously, cover images spread to fit the max width of the containing element. Now they don't, and they're visibly left-aligned. It's not looking great for me.

(from a local build)
![Screen Shot 2020-08-12 at 19 16 52](https://user-images.githubusercontent.com/1312251/90081135-2037eb80-dcd2-11ea-965c-2f9aa8a7e679.png)

I just pulled a bunch of updates from the last month or two, so I'm only seeing this now. I think the issue might be related to placing the cover `img` element inside a `figure` element, perhaps some overridden CSS. I've been unable to figure out exactly what's going on.

I think there are two possible fixes here:
1. Make the cover image stretch to fit the width again. OR
2. Just center whatever image gets put there (not full width).
Whatever you think is better. Let me know if you need more info from my local build.

**Comment by aormsby** [comment]
Ahhh, I've found the root cause of this issue. The `post-cover` class tag was moved from the cover `img` to the containing `figure` element, and that change is applying an unintended set of CSS properties to the figure that should be on the image. I don't currently have a fix, and it might be better to leave this one to you @panr since there is some img css property overlap I don't understand yet.

This change appears in `single.html` and `list.html`.

Before:
```html
{{ if .Params.Cover }}
    {{ if .Params.UseRelativeCover }}
        <img src="{{ (printf "%s%s" .Permalink .Params.Cover ) }}" class="post-cover" />
...
```

After:
```html
{{ if .Params.Cover }}
    <figure class="post-cover">
        {{ if .Params.UseRelativeCover }}
            <img src="{{ (printf "%s%s" .Permalink .Params.Cover ) }}" />
...
```
As you can see from these browser inspector snaps, the incorrect application of the properties is causing some mayhem - incorrect alignment, incorrect width sizing, drop shadow applied to figure container but not the img (3rd image), probably some other things I'm not noticing.

**figure** in the browser inspector.
![Screen Shot 2020-08-14 at 22 53 23](https://user-images.githubusercontent.com/1312251/90304878-ddb51100-de81-11ea-9298-d5e58f30445a.png)

**img** in the browser inspector.
![Screen Shot 2020-08-14 at 22 53 34](https://user-images.githubusercontent.com/1312251/90304880-e1e12e80-de81-11ea-9f46-c019abf1fd73.png)

incorrect drop shadow
![Screen Shot 2020-08-14 at 22 58 48](https://user-images.githubusercontent.com/1312251/90304881-e6a5e280-de81-11ea-9791-299d6115d988.png)

> I think there are two possible fixes here:
> 1. Make the cover image stretch to fit the width again. OR
> 2. Just center whatever image gets put there (not full width).

I am leaning toward fix 2 where the img is centered within the figure. This allows for cover images that are narrower than the layout width and prevents stretching with pixelation. And then fixing misapplied properties, of course (drop shadow bug is really obvious to me).

**Comment by panr** [comment]
@aormsby I'll handle this 👍 Thanks for catching that 🙏

**Comment by ajdintrejic** [comment]
I have a quick fix for that in style.css until it is properly fixed

```
.post-cover > img {
	display: inline-block;
}

.post-cover {
	text-align: center;
}

```

**Comment by panr** [comment]
Fixed it few minutes ago 👍

**Comment by aormsby** [comment]
Haha, I was really worried for a minute because I was still seeing the issue. Then I realized my cache wasn't clearing! I confirm this fix. Thanks for the centering instead of the stretch.
